% plot of energy usage
% @file graph_usage.m
% @author Pavan Dayal

% generate data
data = load('usage.csv');
date = floor(data(:,1));
yr = floor(date / 10000);
mo = floor((date - yr*10000) / 100);
da = floor(date - yr*10000 - mo*100);
hr = data(:,2);
x = datenum([yr, mo, da, hr, zeros(size(hr)), zeros(size(hr))]);
y = data(:,3);
avgy = mean(y)*ones(size(x));

% plot options
resx = 1280;
resy = 720;

% matplotlib colors
% blue:     #1f77b4
% orange:   #ff7f0e
% green:    #2ca02c
% red:      #d62728
% lavender: #9467bd
% brown:    #8c564b

% plot data
H = figure('position', [1,1,resx,resy]);
hold on;

plot(x, y, 'x', ...
    'displayname', 'data', ...
    'color', [214/255, 39/255, 40/255], ...
    'linewidth', 3, ...
    'markersize', 12 ...
);

xticks(linspace(x(1), x(end), floor(length(x)/24)));
datetick('x', '%D', 'keepticks');

plot(x, avgy, '-', ...
    'displayname', sprintf('average: %.7f', mean(y)), ...
    'color', [31/255, 119/255, 180/255], ...
    'linewidth', 4 ...
);

xlim([min(x), max(x)]);
ylim([0,max(y)+1]);

L = legend();
set(L, ...
    'fontsize', 18, ...
    'linewidth', 2, ...
    'textcolor', [0.2, 0.2, 0.2] ...
);

% https://octave.org/doc/v4.2.2/Axes-Properties.html
A = get(H, 'currentaxes');
set(A, ...
    'fontsize', 16, ...
    'linewidth', 2, ...
    'xcolor', [120/255,120/255,120/255], ...
    'ycolor', [120/255,120/255,120/255], ...
    'box', 'on', ...
    'xgrid', 'on', ...
    'ygrid', 'on', ...
    'gridalpha', 0.1 ...
);


% https://octave.org/doc/v4.2.2/Text-Properties.html
Xl = xlabel(sprintf('time\n'), ...
    'fontweight', 'normal', ...
    'fontsize', 28, ...
    'color', [0.2, 0.2 ,0.2] ...
);
set(Xl, 'position', get(Xl,'position')+[0,-0.8,0]);

xlabels = xticklabels();
xt_x = xticks();
xt_y = repmat(get(Xl, 'position')(2) + 1.1, length(xt_x), 1);
set(A, 'xticklabel', []);
xt_H = text(xt_x, xt_y, xlabels);
set(xt_H, ...
    'rotation', 90, ...
    'horizontalalignment', 'right', ...
    'fontweight', 'normal', ...
    'fontsize', 18, ...
    'color', [0.2, 0.2 ,0.2] ...
);

Yl = ylabel('kW', ...
    'fontweight', 'normal', ...
    'fontsize', 28, ...
    'color', [0.2, 0.2 ,0.2] ...
);
set(Yl, 'position', get(Yl,'position')+[-0.2,0,0]);

ylabels = yticklabels();
yt_y = yticks();
yt_x = repmat(get(Yl, 'position')(1)+0.2, length(yt_y), 1);
set(A, 'yticklabel', []);
yt_H = text(yt_x, yt_y, ylabels);
set(yt_H, ...
    'fontweight', 'normal', ...
    'fontsize', 18, ...
    'color', [0.2, 0.2 ,0.2] ...
);

title('energy usage (kW) per hour', ...
    'fontweight', 'normal', ...
    'fontsize', 32, ...
    'color', [0.2, 0.2, 0.2] ...
);

print('usage.png', '-dpng', sprintf('-S%d,%d', resx, resy));
